### ISSUE TITLE
initial code base

### ISSUE THREAD

**Issue by jockmahon** [smichelotti/ng-bootstrap-course#1]
Maybe ive missed something but it would be nice to have a version of the code that matches the "inital app setup" module. As there is quite a lot of code in the inital html pages, it would be a lot to type out, aint nobody got time for that, you end up just coping the final version ie then you already have the code before you even get to the point in the course. Deborah Kurata does this with her courses

**Comment by smichelotti** [comment]
The incremental module-by-module code samples are available in the [Exercise Files](https://app.pluralsight.com/library/courses/ng-bootstrap-playbook/exercise-files) section of the course exactly as you're describing.
